### ISSUE TITLE
一些渲染问题

### ISSUE THREAD

**Issue by oulvhai** [randomatom/hoedown#8]
1. 以下 Markdown， 渲染后网址不会转成连接。

```markdown
### 从 Price Tag 数字商店，购买地址：

<http://h5.youzan.com/v2/showcase/goods?alias=3eruugc3xto5a>

### 从少数派购买，购买地址：

<https://sspai.com/item/13>
```

2. HTML 内容在换行时有时候会被改动，多加些 `<br />` 和 `<p>`

```html
<div class="col-sm-4">
<a href="https://github.com/forrestchang/Cuckoo" target="_blank">
<img class="img-responsive" width="400" src="media/14998541653805/theme-Cuckoo.jpg" /><br />
<h3>Cuckoo</h3>
</a>
<p>A light theme for MWeb. <br />
作者是 <a target="_blank" href="http://forrestchang.com">forrestchang</a><br /><a target="_blank" href="http://forrestchang.com">演示网址</a>
</p>
<br /><br />
</div>

```

以上两个问你看看要不要修。 感谢啦～！！

**Comment by randomatom** [comment]
问题一，我试了一下github的做法，是将两边的 \<\> 符号去掉，渲染中间的链接。
我不太认可该做法。

原文作者加 \<\>的用意可能两种：

1、的确要多加入  \<\>符号，那么github把  \<\>去掉了，不符合原义。
2、不显示  \<\>。那多加  \<\> 根本就是画蛇添足，没有意义。

更简单做法，既然markdown无法处理，就是保留原来字符，不做处理。让html去处理。

该问题不成立，不修改。

**Comment by randomatom** [comment]
问题二，在\<div\>标签中，是按 markdown语法解析，而不是html语法。
这个做法大原则和github是一致的。

差别在于最后的 空行如何处理。github将这些去掉，确比较合理。

修改方式：去掉尾部多余的\<br /\>。其他部分是必须的。

**Comment by oulvhai** [comment]
@randomatom 
问题一，<> 包起来的是之前的 github 认可这种连接语法 `<http://zh.mweb.im>`，现在好像也认可，你试试，当然，也认可不加 <> 的语法。当前的解析的话，如果 < 不在行首第一个字母也能正确解析。所以这个问题当前的解析器其实问题不是很大。

问题二： 原来如此，我是一直认为只要有 html，则中间部分不会处理，原样输出。 其实我也是认为只要有 html，中间部分不会处理比较合适，有利于扩展 markdown 的能力。当然，既然是 github 也是这样处理的，我这种想法就不成立了 :D ， 还是以 github 为标准。

**Comment by randomatom** [comment]
@oulvhai 重新试了一下，在 \<div\> 标签之后，需要「加空行」，才按 markdown 语法解析；
否则按 html 解析。

后面就按这个方式修改。
